version: '3.8'
services:
 server:
   build: .
   ports:
     - "3000:3000"
   environment:
     - DATABASE_URL=mysql://root:kandoitpassword@mysql:3306/kandoit_db
     - JWT_SECRET=your_secret_key_here
   depends_on:
     - mysql


 mysql:
   image: mysql:8.0
   container_name: mysql_container
   environment:
     MYSQL_ROOT_PASSWORD: kandoitpassword 
     MYSQL_DATABASE: kandoit_db         
     MYSQL_PASSWORD: kandoitpassword   
   ports:
     - "3306:3306" 
   volumes:
     - mysql_data:/var/lib/mysql
     - ./testing_schemascript.sql:/docker-entrypoint-initdb.d/seed.sql      


volumes:
 mysql_data: